/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization;
import Business.Role.Role;
import Business.Role.Role.RoleType;
import Business.UserAccount.UserAccount;
import Business.UserAccount.loggedInUser;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lingfeng
 */
public class MainJFrame extends javax.swing.JFrame {
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    UserAccount userAccount;
//    ImageIcon imageIcon = new ImageIcon(new ImageIcon("C:\\Users\\krupa\\Desktop\\AED final project\\singh_sonali_002105639\\FinalProject\\db4odemo\\src\\Icons\\Foster-Family-Coloring.jpg").getImage().getScaledInstance(325, 835, Image.SCALE_DEFAULT));


    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();        
        
//        jLabel2.setIcon(imageIcon);
//    ImageIcon imageIcon = new ImageIcon("C:\\Users\\krupa\\Desktop\\AED final project\\singh_sonali_002105639\\FinalProject\\db4odemo\\src\\Icons\\Foster-Family-Coloring.jpg");
//        Image img = imageIcon.getImage();
//        Image imageScaled = img.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT);
//        ImageIcon scaledIcon = new ImageIcon(imageScaled);
//        jLabel2.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginJPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userNamePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtuserName = new javax.swing.JTextField();
        loginButton = new javax.swing.JLabel();
        passwordPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        loginIconPanel = new javax.swing.JLabel();
        logoutJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginJPanel.setBackground(new java.awt.Color(153, 0, 0));
        loginJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        loginJPanel.setForeground(new java.awt.Color(255, 255, 255));
        loginJPanel.setPreferredSize(new java.awt.Dimension(1200, 802));

        leftPanel.setBackground(new java.awt.Color(204, 204, 204));
        leftPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/foster.jpg"))); // NOI18N

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        userNamePanel.setBackground(new java.awt.Color(153, 0, 0));
        userNamePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        userNamePanel.setPreferredSize(new java.awt.Dimension(302, 34));

        jLabel3.setBackground(new java.awt.Color(153, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/key (2).png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, null, null));

        txtuserName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtuserName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, null, null));
        txtuserName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtuserName.setDisabledTextColor(new java.awt.Color(16, 10, 55));
        txtuserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userNamePanelLayout = new javax.swing.GroupLayout(userNamePanel);
        userNamePanel.setLayout(userNamePanelLayout);
        userNamePanelLayout.setHorizontalGroup(
            userNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userNamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtuserName, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        userNamePanelLayout.setVerticalGroup(
            userNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userNamePanelLayout.createSequentialGroup()
                .addGroup(userNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(txtuserName))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        loginButton.setBackground(new java.awt.Color(81, 53, 103));
        loginButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/loginButtonImg.png"))); // NOI18N
        loginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginButtonMousePressed(evt);
            }
        });

        passwordPanel.setBackground(new java.awt.Color(153, 0, 0));
        passwordPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        passwordPanel.setPreferredSize(new java.awt.Dimension(302, 34));

        jLabel4.setBackground(new java.awt.Color(153, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PasswordIcon.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, null, null));
        jLabel4.setMaximumSize(new java.awt.Dimension(26, 26));
        jLabel4.setMinimumSize(new java.awt.Dimension(26, 26));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, null, null));
        txtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        loginIconPanel.setBackground(new java.awt.Color(255, 153, 0));
        loginIconPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginIconPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/loginLogo.png"))); // NOI18N

        javax.swing.GroupLayout loginJPanelLayout = new javax.swing.GroupLayout(loginJPanel);
        loginJPanel.setLayout(loginJPanelLayout);
        loginJPanelLayout.setHorizontalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginJPanelLayout.createSequentialGroup()
                        .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginJPanelLayout.createSequentialGroup()
                                .addGap(633, 633, 633)
                                .addComponent(loginIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginJPanelLayout.createSequentialGroup()
                                .addGap(574, 574, 574)
                                .addComponent(userNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginJPanelLayout.createSequentialGroup()
                                .addGap(683, 683, 683)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passwordPanel, userNamePanel});

        loginJPanelLayout.setVerticalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(loginIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(userNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {passwordPanel, userNamePanel});

        getContentPane().add(loginJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2200, 1210));

        logoutJPanel.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logoutJPanelLayout = new javax.swing.GroupLayout(logoutJPanel);
        logoutJPanel.setLayout(logoutJPanelLayout);
        logoutJPanelLayout.setHorizontalGroup(
            logoutJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutJPanelLayout.setVerticalGroup(
            logoutJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutJPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(logoutJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        container.setBackground(new java.awt.Color(153, 0, 0));
        container.setForeground(new java.awt.Color(255, 255, 255));
        container.setPreferredSize(new java.awt.Dimension(2193, 1202));
        container.setLayout(new java.awt.CardLayout());
        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        // TODO add your handling code here:
        String userName = txtuserName.getText();
        String password = String.valueOf(txtPassword.getPassword());
        userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);
        if(userAccount==null)
                {
                    for(Network networks:system.getNetworks())
                    {
                        for(Enterprise enterprises:networks.getEnterpriseDirectory().getEnterprises())
                        {
                            userAccount=enterprises.getUserAccountDirectory().authenticateUser(userName, password);
                            if(userAccount!=null)
                            {
                                break;
                            }
                            if(userAccount==null)
                            {
                                for(Organization organisation: enterprises.getOrganizationDirectory().getOrganisationList())
                                {
                                   userAccount=organisation.getUserAccountDirectory().authenticateUser(userName, password);
                                   if(userAccount!=null)
                                   {
                                       break;
                                   }
                                }
                                
                            }
                            if(userAccount!=null)
                            {
                                break;
                            }
                        }
                        if(userAccount!=null)
                        {
                            break;
                        }
                    }
                }
        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Please enter valid login credentials");
            return;
        }else{
            loginJPanel.setVisible(false);
            container.setVisible(true);
            txtuserName.setText("");
            txtPassword.setText("");
            leftPanel.setVisible(true);
            for (UserAccount userAccount : system.getUserAccountDirectory().getUserAccountList()) {
               if(userAccount.getUsername().equals(userName))
               {
                   loggedInUser logInUser=new loggedInUser();
                   logInUser.setLogInId(userAccount.getUniqueId());
                   //system.setLogInUser(logInUser);
               }
            }
             for(Network networks:system.getNetworks())
            {
                for(Enterprise enterprises:networks.getEnterpriseDirectory().getEnterprises())
                {
                    for(UserAccount userAccount:enterprises.getUserAccountDirectory().getUserAccountList())
                    {
                        if(userAccount.getUsername().equals(userName))
                        {
                            loggedInUser logInUser=new loggedInUser();
                            logInUser.setLogInId(userAccount.getUniqueId());
                            system.setLogInUser(logInUser);
                            break;
                        }
                    }
                }
            }
             for(Network networks:system.getNetworks())
            {
                for(Enterprise enterprises:networks.getEnterpriseDirectory().getEnterprises())
                {
                    for(Organization organisation:enterprises.getOrganizationDirectory().getOrganisationList())
                    {
                        for(UserAccount userAccount:organisation.getUserAccountDirectory().getUserAccountList())
                        {
                            if(userAccount.getUsername().equals(userName))
                            {
                                loggedInUser logInUser=new loggedInUser();
                                logInUser.setLogInId(userAccount.getUniqueId());
                                system.setLogInUser(logInUser);
                                break;
                            }
                        }
                    }
                }
            }
            switchJPanel(userAccount);
            
        }

    }//GEN-LAST:event_loginButtonMousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        container.removeAll();
        dB4OUtil.storeSystem(system);
        loginJPanel.setVisible(true);
        container.setVisible(false);
        leftPanel.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtuserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed
    private void switchJPanel(UserAccount loggedInUser) {
        String abc=RoleType.OrganizationAdmin.name();
    Role xyz=loggedInUser.getRole();
        if (loggedInUser != null) {
            if(loggedInUser.getRole().equals(RoleType.OrganizationAdmin.name()))
            {
                container.add("workArea", loggedInUser.getRole().createWorkArea(container,loggedInUser,system));
            }
            if(loggedInUser.getRole().equals(RoleType.RestaurantAdmin.toString())){
                container.add("workArea", loggedInUser.getRole().createWorkArea(container,loggedInUser,system));
            }
            else if (loggedInUser.getRole().equals(Role.RoleType.NGOEmployee.toString())){
                container.add("workArea", loggedInUser.getRole().createWorkArea(container,loggedInUser,system));
            }
            else if(loggedInUser.getRole().equals(RoleType.DeliveryMan.toString())){
                container.add("workArea", loggedInUser.getRole().createWorkArea(container,loggedInUser,system));
            }
            else{
                container.add("workArea", loggedInUser.getRole().createWorkArea(container, loggedInUser, system));
            }
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel loginButton;
    private javax.swing.JLabel loginIconPanel;
    private javax.swing.JPanel loginJPanel;
    private javax.swing.JPanel logoutJPanel;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtuserName;
    private javax.swing.JPanel userNamePanel;
    // End of variables declaration//GEN-END:variables
}
